DROP TABLE IF EXISTS product_ranks;

CREATE TABLE product_ranks
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_date VARCHAR(20) NOT NULL,
    serial_number VARCHAR(20) NOT NULL,
    keywords VARCHAR(200) NOT NULL,
    rank INT
);
